---
- hosts: all
  user: root
  tasks:

  - name: put ssh-key for root
    authorized_key: user=root key="{{lookup('file', '~/.ssh/id_dsa.pub') }}" manage_dir=yes #" 

  - name: create ssh key for root
    user: name=root generate_ssh_key=yes ssh_key_bits=2048

  - name: install basic packages
    apt: pkg={{ item }} state=installed
    with_items:
       - sudo
       - screen
       - iotop 
       - iptraf 
       - vim
       - netcat
       - telnet
       - zip 
       - unzip 
       - wget 
       - etckeeper 
       - links 
       - bash-completion 
       - dstat 
       - links 
       - ntp 
       - ssh
       - sysstat 
       - lzop 
       - atop 
       - mosh
       - linuxlogo

  - name: create user guerre
    user: name=guerre uid=1000 shell=/bin/bash groups=adm

  - name: add user guerre ssh-key
    authorized_key: user=guerre key="{{lookup('file', '~/.ssh/id_dsa.pub') }}" manage_dir=yes #" 

  - name: change motd 
    action: copy src=/etc/issue.linuxlogo dest=/etc/motd 
